/*
 * Swagger ItaliaTreni - OpenAPI 3.0
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Domain.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Measure : IEquatable<Measure>
    {
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Mm
        /// </summary>

        [DataMember(Name="mm")]
        public long? mm { get; set; }

        /// <summary>
        /// Gets or Sets P1
        /// </summary>

        [DataMember(Name="p1")]
        public double? P1 { get; set; } = 0;

        /// <summary>
        /// Gets or Sets P2
        /// </summary>

        [DataMember(Name="p2")]
        public double? P2 { get; set; } = 0;

        /// <summary>
        /// Gets or Sets P3
        /// </summary>

        [DataMember(Name="p3")]
        public double? P3 { get; set; } = 0;

        /// <summary>
        /// Gets or Sets P4
        /// </summary>

        [DataMember(Name = "p4")]
        public double? P4 { get; set; } = 0;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Measure {\n");
            sb.Append("  mm: ").Append(mm).Append("\n");
            sb.Append("  P1: ").Append(P1).Append("\n");
            sb.Append("  P2: ").Append(P2).Append("\n");
            sb.Append("  P3: ").Append(P3).Append("\n");
            sb.Append("  P4: ").Append(P4).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Measure)obj);
        }

        /// <summary>
        /// Returns true if Measure instances are equal
        /// </summary>
        /// <param name="other">Instance of Measure to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Measure other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                
                (
                    mm == other.mm ||
                    mm != null &&
                    mm.Equals(other.mm)
                ) && 
                (
                    P1 == other.P1 ||
                    P1 != null &&
                    P1.Equals(other.P1)
                ) && 
                (
                    P2 == other.P2 ||
                    P2 != null &&
                    P2.Equals(other.P2)
                ) && 
                (
                    P3 == other.P3 ||
                    P3 != null &&
                    P3.Equals(other.P3)
                ) && 
                (
                    P4 == other.P4 ||
                    P4 != null &&
                    P4.Equals(other.P4)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (mm != null)
                    hashCode = hashCode * 59 + mm.GetHashCode();
                    if (P1 != null)
                    hashCode = hashCode * 59 + P1.GetHashCode();
                    if (P2 != null)
                    hashCode = hashCode * 59 + P2.GetHashCode();
                    if (P3 != null)
                    hashCode = hashCode * 59 + P3.GetHashCode();
                    if (P4 != null)
                    hashCode = hashCode * 59 + P4.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Measure left, Measure right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Measure left, Measure right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
